/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class admin01 extends javax.swing.JPanel {

    /**
     * Creates new form admin01
     */
    public admin01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanel = new javax.swing.JPanel();
        adminLabel01 = new javax.swing.JLabel();
        adminLabel02 = new javax.swing.JLabel();
        adminLabel04 = new javax.swing.JLabel();
        adminLabel05 = new javax.swing.JLabel();
        employeeNum_admin = new javax.swing.JComboBox<>();
        adminLabel03 = new javax.swing.JLabel();
        empPasswd_admin = new javax.swing.JLabel();
        empDepat_admin = new javax.swing.JLabel();
        employeeName_admin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        adminLabel06 = new javax.swing.JLabel();
        adminLabel07 = new javax.swing.JLabel();
        adminLabel08 = new javax.swing.JLabel();
        employeeY_admin = new javax.swing.JRadioButton();
        employeeN_admin = new javax.swing.JRadioButton();
        adminLabel10 = new javax.swing.JLabel();
        adminLabel11 = new javax.swing.JLabel();
        attendanceY_admin = new javax.swing.JRadioButton();
        achievementY_admin = new javax.swing.JRadioButton();
        payRollY_admin = new javax.swing.JRadioButton();
        purchaseY_admin = new javax.swing.JRadioButton();
        attendanceN_admin = new javax.swing.JRadioButton();
        achievementN_admin = new javax.swing.JRadioButton();
        payRollN_admin = new javax.swing.JRadioButton();
        purchaseN_admin = new javax.swing.JRadioButton();
        adminLabel12 = new javax.swing.JLabel();
        adminLabel13 = new javax.swing.JLabel();
        adminLabel14 = new javax.swing.JLabel();
        materialY_admin = new javax.swing.JRadioButton();
        orderListY_admin = new javax.swing.JRadioButton();
        orderItemY_admin = new javax.swing.JRadioButton();
        issueY_admin = new javax.swing.JRadioButton();
        payableListY_admin = new javax.swing.JRadioButton();
        materialN_admin = new javax.swing.JRadioButton();
        orderListN_admin = new javax.swing.JRadioButton();
        orderItemN_admin = new javax.swing.JRadioButton();
        issueN_admin = new javax.swing.JRadioButton();
        payableListN_admin = new javax.swing.JRadioButton();
        adminLabel15 = new javax.swing.JLabel();
        adminLabel16 = new javax.swing.JLabel();
        adminLabel17 = new javax.swing.JLabel();
        adminLabel18 = new javax.swing.JLabel();
        adminLabel19 = new javax.swing.JLabel();
        adminLabel09 = new javax.swing.JLabel();
        productY_admin = new javax.swing.JRadioButton();
        assetY_admin = new javax.swing.JRadioButton();
        productN_admin = new javax.swing.JRadioButton();
        assetN_admin = new javax.swing.JRadioButton();
        memberY_admin = new javax.swing.JRadioButton();
        vendorY_admin = new javax.swing.JRadioButton();
        adminY_admin = new javax.swing.JRadioButton();
        billboardY_admin = new javax.swing.JRadioButton();
        memberN_admin = new javax.swing.JRadioButton();
        vendorN_admin = new javax.swing.JRadioButton();
        adminN_admin = new javax.swing.JRadioButton();
        billboardN_admin = new javax.swing.JRadioButton();
        adminLabel20 = new javax.swing.JLabel();
        note_admin = new javax.swing.JTextField();
        testBtn = new javax.swing.JButton();

        adminPanel.setMinimumSize(new java.awt.Dimension(980, 470));
        adminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminLabel01.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel01.setText("員工編號");
        adminPanel.add(adminLabel01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        adminLabel02.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel02.setText("登入密碼");
        adminPanel.add(adminLabel02, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 10, -1, 30));

        adminLabel04.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel04.setText("員工資料表");
        adminPanel.add(adminLabel04, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 87, -1, 30));

        adminLabel05.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel05.setText("出缺勤表");
        adminPanel.add(adminLabel05, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 146, -1, 30));

        employeeNum_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeNum_admin.setForeground(new java.awt.Color(0, 0, 204));
        employeeNum_admin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        adminPanel.add(employeeNum_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 10, 149, 30));

        adminLabel03.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel03.setText("所屬單位");
        adminPanel.add(adminLabel03, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 10, -1, 30));

        empPasswd_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        empPasswd_admin.setForeground(new java.awt.Color(0, 0, 204));
        empPasswd_admin.setText("密碼");
        adminPanel.add(empPasswd_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 187, 30));

        empDepat_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        empDepat_admin.setForeground(new java.awt.Color(0, 0, 204));
        empDepat_admin.setText("部門");
        adminPanel.add(empDepat_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 145, 30));

        employeeName_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeName_admin.setForeground(new java.awt.Color(0, 0, 204));
        employeeName_admin.setText("帶出員工姓名");
        adminPanel.add(employeeName_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 10, -1, 30));
        adminPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 980, 10));

        adminLabel06.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel06.setText("員工考績表");
        adminPanel.add(adminLabel06, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 208, -1, -1));

        adminLabel07.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel07.setText("薪資表");
        adminPanel.add(adminLabel07, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 267, -1, -1));

        adminLabel08.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel08.setText("進貨表");
        adminPanel.add(adminLabel08, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 326, -1, -1));

        employeeY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeY_admin.setText("Yes");
        adminPanel.add(employeeY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 86, -1, -1));

        employeeN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeN_admin.setText("No");
        adminPanel.add(employeeN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 86, -1, -1));

        adminLabel10.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel10.setText("原料庫存表");
        adminPanel.add(adminLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 90, -1, -1));

        adminLabel11.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel11.setText("訂單資料表");
        adminPanel.add(adminLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 149, -1, -1));

        attendanceY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        attendanceY_admin.setText("Yes");
        adminPanel.add(attendanceY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 145, -1, -1));

        achievementY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        achievementY_admin.setText("Yes");
        adminPanel.add(achievementY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 204, -1, -1));

        payRollY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        payRollY_admin.setText("Yes");
        adminPanel.add(payRollY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 263, -1, -1));

        purchaseY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseY_admin.setText("Yes");
        adminPanel.add(purchaseY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 322, -1, -1));

        attendanceN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        attendanceN_admin.setText("No");
        adminPanel.add(attendanceN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 145, -1, -1));

        achievementN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        achievementN_admin.setText("No");
        adminPanel.add(achievementN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 204, -1, -1));

        payRollN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        payRollN_admin.setText("No");
        adminPanel.add(payRollN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 263, -1, -1));

        purchaseN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseN_admin.setText("No");
        adminPanel.add(purchaseN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 322, -1, -1));

        adminLabel12.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel12.setText("訂購項目表");
        adminPanel.add(adminLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 208, -1, -1));

        adminLabel13.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel13.setText("異常資料表");
        adminPanel.add(adminLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 267, -1, -1));

        adminLabel14.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel14.setText("應收管理表");
        adminPanel.add(adminLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 326, -1, -1));

        materialY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        materialY_admin.setText("Yes");
        adminPanel.add(materialY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 86, -1, -1));

        orderListY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        orderListY_admin.setText("Yes");
        adminPanel.add(orderListY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 145, -1, -1));

        orderItemY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        orderItemY_admin.setText("Yes");
        adminPanel.add(orderItemY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 204, -1, -1));

        issueY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        issueY_admin.setText("Yes");
        adminPanel.add(issueY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 263, -1, -1));

        payableListY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        payableListY_admin.setText("Yes");
        adminPanel.add(payableListY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 322, -1, -1));

        materialN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        materialN_admin.setText("No");
        adminPanel.add(materialN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 86, -1, -1));

        orderListN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        orderListN_admin.setText("No");
        adminPanel.add(orderListN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 145, -1, -1));

        orderItemN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        orderItemN_admin.setText("No");
        adminPanel.add(orderItemN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 204, -1, -1));

        issueN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        issueN_admin.setText("No");
        adminPanel.add(issueN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 263, -1, -1));

        payableListN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        payableListN_admin.setText("No");
        adminPanel.add(payableListN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 322, -1, -1));

        adminLabel15.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel15.setText("資產管理表");
        adminPanel.add(adminLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 389, -1, -1));

        adminLabel16.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel16.setText("客戶資料表");
        adminPanel.add(adminLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 90, -1, -1));

        adminLabel17.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel17.setText("廠商資料表");
        adminPanel.add(adminLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 149, -1, -1));

        adminLabel18.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel18.setText("帳號管理表");
        adminPanel.add(adminLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 208, -1, -1));

        adminLabel19.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel19.setText("公告管理表");
        adminPanel.add(adminLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 267, -1, -1));

        adminLabel09.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel09.setText("產品資料表");
        adminPanel.add(adminLabel09, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 389, -1, -1));

        productY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        productY_admin.setText("Yes");
        adminPanel.add(productY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 385, -1, -1));

        assetY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetY_admin.setText("Yes");
        adminPanel.add(assetY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 385, -1, -1));

        productN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        productN_admin.setText("No");
        adminPanel.add(productN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 385, -1, -1));

        assetN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetN_admin.setText("No");
        adminPanel.add(assetN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 385, -1, -1));

        memberY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        memberY_admin.setText("Yes");
        adminPanel.add(memberY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 86, -1, -1));

        vendorY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        vendorY_admin.setText("Yes");
        adminPanel.add(vendorY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 145, -1, -1));

        adminY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminY_admin.setText("Yes");
        adminPanel.add(adminY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 204, -1, -1));

        billboardY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardY_admin.setText("Yes");
        adminPanel.add(billboardY_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 263, -1, -1));

        memberN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        memberN_admin.setText("No");
        adminPanel.add(memberN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 86, -1, -1));

        vendorN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        vendorN_admin.setText("No");
        adminPanel.add(vendorN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 145, -1, -1));

        adminN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminN_admin.setText("No");
        adminPanel.add(adminN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 204, -1, -1));

        billboardN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardN_admin.setText("No");
        adminPanel.add(billboardN_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 263, -1, -1));

        adminLabel20.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel20.setText("備註");
        adminPanel.add(adminLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 326, 90, -1));

        note_admin.setMaximumSize(new java.awt.Dimension(160, 30));
        note_admin.setMinimumSize(new java.awt.Dimension(160, 30));
        note_admin.setPreferredSize(new java.awt.Dimension(160, 30));
        adminPanel.add(note_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 326, 201, 33));

        testBtn.setText("test");
        testBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testBtnActionPerformed(evt);
            }
        });
        adminPanel.add(testBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 394, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void testBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testBtnActionPerformed

    public static void main(String[] arg){
        admin01 admin01 = new admin01();
        admin01.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton achievementN_admin;
    private javax.swing.JRadioButton achievementY_admin;
    private javax.swing.JLabel adminLabel01;
    private javax.swing.JLabel adminLabel02;
    private javax.swing.JLabel adminLabel03;
    private javax.swing.JLabel adminLabel04;
    private javax.swing.JLabel adminLabel05;
    private javax.swing.JLabel adminLabel06;
    private javax.swing.JLabel adminLabel07;
    private javax.swing.JLabel adminLabel08;
    private javax.swing.JLabel adminLabel09;
    private javax.swing.JLabel adminLabel10;
    private javax.swing.JLabel adminLabel11;
    private javax.swing.JLabel adminLabel12;
    private javax.swing.JLabel adminLabel13;
    private javax.swing.JLabel adminLabel14;
    private javax.swing.JLabel adminLabel15;
    private javax.swing.JLabel adminLabel16;
    private javax.swing.JLabel adminLabel17;
    private javax.swing.JLabel adminLabel18;
    private javax.swing.JLabel adminLabel19;
    private javax.swing.JLabel adminLabel20;
    private javax.swing.JRadioButton adminN_admin;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JRadioButton adminY_admin;
    private javax.swing.JRadioButton assetN_admin;
    private javax.swing.JRadioButton assetY_admin;
    private javax.swing.JRadioButton attendanceN_admin;
    private javax.swing.JRadioButton attendanceY_admin;
    private javax.swing.JRadioButton billboardN_admin;
    private javax.swing.JRadioButton billboardY_admin;
    private javax.swing.JLabel empDepat_admin;
    private javax.swing.JLabel empPasswd_admin;
    private javax.swing.JRadioButton employeeN_admin;
    private javax.swing.JLabel employeeName_admin;
    private javax.swing.JComboBox<String> employeeNum_admin;
    private javax.swing.JRadioButton employeeY_admin;
    private javax.swing.JRadioButton issueN_admin;
    private javax.swing.JRadioButton issueY_admin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton materialN_admin;
    private javax.swing.JRadioButton materialY_admin;
    private javax.swing.JRadioButton memberN_admin;
    private javax.swing.JRadioButton memberY_admin;
    private javax.swing.JTextField note_admin;
    private javax.swing.JRadioButton orderItemN_admin;
    private javax.swing.JRadioButton orderItemY_admin;
    private javax.swing.JRadioButton orderListN_admin;
    private javax.swing.JRadioButton orderListY_admin;
    private javax.swing.JRadioButton payRollN_admin;
    private javax.swing.JRadioButton payRollY_admin;
    private javax.swing.JRadioButton payableListN_admin;
    private javax.swing.JRadioButton payableListY_admin;
    private javax.swing.JRadioButton productN_admin;
    private javax.swing.JRadioButton productY_admin;
    private javax.swing.JRadioButton purchaseN_admin;
    private javax.swing.JRadioButton purchaseY_admin;
    private javax.swing.JButton testBtn;
    private javax.swing.JRadioButton vendorN_admin;
    private javax.swing.JRadioButton vendorY_admin;
    // End of variables declaration//GEN-END:variables
}
