/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
        nowLayout = new CardLayout();       
        panel_dataInput.setLayout(nowLayout);
        panel_dataInput.add(admin,"adminPanel");
        nowLayout.show(panel_dataInput, "adminPanel");    
*/

/**
 *
 * @author asus
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employee_admin = new javax.swing.ButtonGroup();
        attendance_admin = new javax.swing.ButtonGroup();
        achievement_admin = new javax.swing.ButtonGroup();
        payRoll_admin = new javax.swing.ButtonGroup();
        purchase_admin = new javax.swing.ButtonGroup();
        product_admin = new javax.swing.ButtonGroup();
        material_admin = new javax.swing.ButtonGroup();
        orderList_admin = new javax.swing.ButtonGroup();
        orderItem_admin = new javax.swing.ButtonGroup();
        issue_admin = new javax.swing.ButtonGroup();
        payableList_admin = new javax.swing.ButtonGroup();
        asset_admin = new javax.swing.ButtonGroup();
        vendor_admin = new javax.swing.ButtonGroup();
        adminList_admin = new javax.swing.ButtonGroup();
        billboard_admin = new javax.swing.ButtonGroup();
        member_admin = new javax.swing.ButtonGroup();
        sales_admin = new javax.swing.ButtonGroup();
        profit_admin = new javax.swing.ButtonGroup();
        adminPanel = new javax.swing.JPanel();
        adminLabel01 = new javax.swing.JLabel();
        adminLabel02 = new javax.swing.JLabel();
        adminLabel04 = new javax.swing.JLabel();
        adminLabel05 = new javax.swing.JLabel();
        employeeNum_admin = new javax.swing.JComboBox<>();
        adminLabel03 = new javax.swing.JLabel();
        empPasswd_admin = new javax.swing.JLabel();
        empDepat_admin = new javax.swing.JLabel();
        employeeName_admin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        adminLabel06 = new javax.swing.JLabel();
        adminLabel07 = new javax.swing.JLabel();
        adminLabel08 = new javax.swing.JLabel();
        employeeY_admin = new javax.swing.JRadioButton();
        employeeN_admin = new javax.swing.JRadioButton();
        adminLabel10 = new javax.swing.JLabel();
        adminLabel11 = new javax.swing.JLabel();
        attendanceY_admin = new javax.swing.JRadioButton();
        achievementY_admin = new javax.swing.JRadioButton();
        payRollY_admin = new javax.swing.JRadioButton();
        purchaseY_admin = new javax.swing.JRadioButton();
        attendanceN_admin = new javax.swing.JRadioButton();
        achievementN_admin = new javax.swing.JRadioButton();
        payRollN_admin = new javax.swing.JRadioButton();
        purchaseN_admin = new javax.swing.JRadioButton();
        adminLabel12 = new javax.swing.JLabel();
        adminLabel13 = new javax.swing.JLabel();
        adminLabel14 = new javax.swing.JLabel();
        materialY_admin = new javax.swing.JRadioButton();
        orderListY_admin = new javax.swing.JRadioButton();
        orderItemY_admin = new javax.swing.JRadioButton();
        issueY_admin = new javax.swing.JRadioButton();
        payableListY_admin = new javax.swing.JRadioButton();
        materialN_admin = new javax.swing.JRadioButton();
        orderListN_admin = new javax.swing.JRadioButton();
        orderItemN_admin = new javax.swing.JRadioButton();
        issueN_admin = new javax.swing.JRadioButton();
        payableListN_admin = new javax.swing.JRadioButton();
        adminLabel15 = new javax.swing.JLabel();
        adminLabel16 = new javax.swing.JLabel();
        adminLabel17 = new javax.swing.JLabel();
        adminLabel18 = new javax.swing.JLabel();
        adminLabel19 = new javax.swing.JLabel();
        adminLabel09 = new javax.swing.JLabel();
        productY_admin = new javax.swing.JRadioButton();
        assetY_admin = new javax.swing.JRadioButton();
        productN_admin = new javax.swing.JRadioButton();
        assetN_admin = new javax.swing.JRadioButton();
        memberY_admin = new javax.swing.JRadioButton();
        vendorY_admin = new javax.swing.JRadioButton();
        adminY_admin = new javax.swing.JRadioButton();
        billboardY_admin = new javax.swing.JRadioButton();
        memberN_admin = new javax.swing.JRadioButton();
        vendorN_admin = new javax.swing.JRadioButton();
        adminN_admin = new javax.swing.JRadioButton();
        billboardN_admin = new javax.swing.JRadioButton();
        adminLabel20 = new javax.swing.JLabel();
        note_admin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        profitY_admin = new javax.swing.JRadioButton();
        profitN_admin = new javax.swing.JRadioButton();
        salesN_admin = new javax.swing.JRadioButton();
        salesY_admin = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 470));

        adminPanel.setMinimumSize(new java.awt.Dimension(980, 470));

        adminLabel01.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel01.setText("員工編號");

        adminLabel02.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel02.setText("登入密碼");

        adminLabel04.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel04.setText("員工資料表");

        adminLabel05.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel05.setText("出缺勤表");

        employeeNum_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeNum_admin.setForeground(new java.awt.Color(0, 0, 204));
        employeeNum_admin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employeeNum_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNum_adminActionPerformed(evt);
            }
        });

        adminLabel03.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel03.setText("所屬單位");

        empPasswd_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        empPasswd_admin.setForeground(new java.awt.Color(0, 0, 204));
        empPasswd_admin.setText("密碼");

        empDepat_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        empDepat_admin.setForeground(new java.awt.Color(0, 0, 204));
        empDepat_admin.setText("部門");

        employeeName_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeName_admin.setForeground(new java.awt.Color(0, 0, 204));
        employeeName_admin.setText("帶出員工姓名");

        adminLabel06.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel06.setText("員工考績表");

        adminLabel07.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel07.setText("薪資表");

        adminLabel08.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel08.setText("進貨表");

        employee_admin.add(employeeY_admin);
        employeeY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeY_admin.setText("Yes");

        employee_admin.add(employeeN_admin);
        employeeN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeN_admin.setText("No");

        adminLabel10.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel10.setText("原料庫存表");

        adminLabel11.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel11.setText("訂單資料表");

        attendance_admin.add(attendanceY_admin);
        attendanceY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        attendanceY_admin.setText("Yes");

        achievement_admin.add(achievementY_admin);
        achievementY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        achievementY_admin.setText("Yes");

        payRoll_admin.add(payRollY_admin);
        payRollY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        payRollY_admin.setText("Yes");

        purchase_admin.add(purchaseY_admin);
        purchaseY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseY_admin.setText("Yes");

        attendance_admin.add(attendanceN_admin);
        attendanceN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        attendanceN_admin.setText("No");

        achievement_admin.add(achievementN_admin);
        achievementN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        achievementN_admin.setText("No");

        payRoll_admin.add(payRollN_admin);
        payRollN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        payRollN_admin.setText("No");

        purchase_admin.add(purchaseN_admin);
        purchaseN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseN_admin.setText("No");

        adminLabel12.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel12.setText("訂購項目表");

        adminLabel13.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel13.setText("異常資料表");

        adminLabel14.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel14.setText("應收管理表");

        material_admin.add(materialY_admin);
        materialY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        materialY_admin.setText("Yes");

        orderList_admin.add(orderListY_admin);
        orderListY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        orderListY_admin.setText("Yes");

        orderItem_admin.add(orderItemY_admin);
        orderItemY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        orderItemY_admin.setText("Yes");

        issue_admin.add(issueY_admin);
        issueY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        issueY_admin.setText("Yes");

        payableList_admin.add(payableListY_admin);
        payableListY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        payableListY_admin.setText("Yes");

        material_admin.add(materialN_admin);
        materialN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        materialN_admin.setText("No");

        orderList_admin.add(orderListN_admin);
        orderListN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        orderListN_admin.setText("No");

        orderItem_admin.add(orderItemN_admin);
        orderItemN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        orderItemN_admin.setText("No");

        issue_admin.add(issueN_admin);
        issueN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        issueN_admin.setText("No");

        payableList_admin.add(payableListN_admin);
        payableListN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        payableListN_admin.setText("No");

        adminLabel15.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel15.setText("資產管理表");

        adminLabel16.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel16.setText("客戶資料表");

        adminLabel17.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel17.setText("廠商資料表");

        adminLabel18.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel18.setText("帳號管理表");

        adminLabel19.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel19.setText("公告管理表");

        adminLabel09.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel09.setText("產品資料表");

        product_admin.add(productY_admin);
        productY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        productY_admin.setText("Yes");

        asset_admin.add(assetY_admin);
        assetY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetY_admin.setText("Yes");

        product_admin.add(productN_admin);
        productN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        productN_admin.setText("No");

        asset_admin.add(assetN_admin);
        assetN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetN_admin.setText("No");

        member_admin.add(memberY_admin);
        memberY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        memberY_admin.setText("Yes");

        vendor_admin.add(vendorY_admin);
        vendorY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        vendorY_admin.setText("Yes");

        adminList_admin.add(adminY_admin);
        adminY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminY_admin.setText("Yes");

        billboard_admin.add(billboardY_admin);
        billboardY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardY_admin.setText("Yes");

        member_admin.add(memberN_admin);
        memberN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        memberN_admin.setText("No");

        vendor_admin.add(vendorN_admin);
        vendorN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        vendorN_admin.setText("No");

        adminList_admin.add(adminN_admin);
        adminN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminN_admin.setText("No");

        billboard_admin.add(billboardN_admin);
        billboardN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardN_admin.setText("No");

        adminLabel20.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        adminLabel20.setText("備註");

        note_admin.setMaximumSize(new java.awt.Dimension(160, 30));
        note_admin.setMinimumSize(new java.awt.Dimension(160, 30));
        note_admin.setPreferredSize(new java.awt.Dimension(160, 30));

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel1.setText("營利報表");

        profit_admin.add(profitY_admin);
        profitY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        profitY_admin.setText("Yes");
        profitY_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitY_adminActionPerformed(evt);
            }
        });

        profit_admin.add(profitN_admin);
        profitN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        profitN_admin.setText("No");

        sales_admin.add(salesN_admin);
        salesN_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        salesN_admin.setText("No");

        sales_admin.add(salesY_admin);
        salesY_admin.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        salesY_admin.setText("Yes");

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel2.setText("銷售報表");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(adminLabel01)
                        .addGap(10, 10, 10)
                        .addComponent(employeeNum_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(employeeName_admin)
                        .addGap(75, 75, 75)
                        .addComponent(adminLabel02)
                        .addGap(10, 10, 10)
                        .addComponent(empPasswd_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(adminLabel03)
                        .addGap(6, 6, 6)
                        .addComponent(empDepat_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(adminLabel04)
                        .addGap(18, 18, 18)
                        .addComponent(employeeY_admin)
                        .addGap(12, 12, 12)
                        .addComponent(employeeN_admin)
                        .addGap(72, 72, 72)
                        .addComponent(adminLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(materialY_admin)
                        .addGap(12, 12, 12)
                        .addComponent(materialN_admin)
                        .addGap(72, 72, 72)
                        .addComponent(adminLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(memberY_admin)
                        .addGap(12, 12, 12)
                        .addComponent(memberN_admin))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(adminLabel05)
                        .addGap(36, 36, 36)
                        .addComponent(attendanceY_admin)
                        .addGap(12, 12, 12)
                        .addComponent(attendanceN_admin)
                        .addGap(72, 72, 72)
                        .addComponent(adminLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(orderListY_admin)
                        .addGap(12, 12, 12)
                        .addComponent(orderListN_admin)
                        .addGap(72, 72, 72)
                        .addComponent(adminLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(vendorY_admin)
                        .addGap(12, 12, 12)
                        .addComponent(vendorN_admin))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(adminLabel06)
                        .addGap(18, 18, 18)
                        .addComponent(achievementY_admin)
                        .addGap(12, 12, 12)
                        .addComponent(achievementN_admin)
                        .addGap(72, 72, 72)
                        .addComponent(adminLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(orderItemY_admin)
                        .addGap(12, 12, 12)
                        .addComponent(orderItemN_admin)
                        .addGap(72, 72, 72)
                        .addComponent(adminLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(adminY_admin)
                        .addGap(12, 12, 12)
                        .addComponent(adminN_admin))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addComponent(adminLabel07)
                                .addGap(54, 54, 54)
                                .addComponent(payRollY_admin)
                                .addGap(12, 12, 12)
                                .addComponent(payRollN_admin)
                                .addGap(72, 72, 72)
                                .addComponent(adminLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(issueY_admin)
                                .addGap(12, 12, 12)
                                .addComponent(issueN_admin))
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addComponent(adminLabel08)
                                .addGap(54, 54, 54)
                                .addComponent(purchaseY_admin)
                                .addGap(12, 12, 12)
                                .addComponent(purchaseN_admin)
                                .addGap(72, 72, 72)
                                .addComponent(adminLabel14)
                                .addGap(6, 6, 6)
                                .addComponent(payableListY_admin)
                                .addGap(12, 12, 12)
                                .addComponent(payableListN_admin))
                            .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(adminPanelLayout.createSequentialGroup()
                                    .addComponent(adminLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(note_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(adminPanelLayout.createSequentialGroup()
                                    .addComponent(adminLabel09)
                                    .addGap(18, 18, 18)
                                    .addComponent(productY_admin)
                                    .addGap(12, 12, 12)
                                    .addComponent(productN_admin)
                                    .addGap(72, 72, 72)
                                    .addComponent(adminLabel15)
                                    .addGap(6, 6, 6)
                                    .addComponent(assetY_admin)
                                    .addGap(12, 12, 12)
                                    .addComponent(assetN_admin))))
                        .addGap(72, 72, 72)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(adminLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addComponent(billboardY_admin)
                                .addGap(18, 18, 18)
                                .addComponent(billboardN_admin))
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(salesY_admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(profitY_admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(profitN_admin)
                                    .addComponent(salesN_admin))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeNum_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeName_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLabel02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empPasswd_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLabel03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empDepat_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(adminLabel04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(employeeY_admin)
                    .addComponent(employeeN_admin)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(adminLabel10))
                    .addComponent(materialY_admin)
                    .addComponent(materialN_admin)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(adminLabel16))
                    .addComponent(memberY_admin)
                    .addComponent(memberN_admin))
                .addGap(20, 20, 20)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(adminLabel05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(attendanceY_admin)
                    .addComponent(attendanceN_admin)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(adminLabel11))
                    .addComponent(orderListY_admin)
                    .addComponent(orderListN_admin)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(adminLabel17))
                    .addComponent(vendorY_admin)
                    .addComponent(vendorN_admin))
                .addGap(20, 20, 20)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(achievementY_admin)
                    .addComponent(achievementN_admin)
                    .addComponent(orderItemY_admin)
                    .addComponent(orderItemN_admin)
                    .addComponent(adminY_admin)
                    .addComponent(adminN_admin)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminLabel06)
                            .addComponent(adminLabel12)
                            .addComponent(adminLabel18))))
                .addGap(20, 20, 20)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payRollY_admin)
                    .addComponent(payRollN_admin)
                    .addComponent(issueY_admin)
                    .addComponent(issueN_admin)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminLabel07)
                            .addComponent(adminLabel13)
                            .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(adminLabel19)
                                .addComponent(billboardY_admin)
                                .addComponent(billboardN_admin)))))
                .addGap(20, 20, 20)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(purchaseY_admin)
                            .addComponent(purchaseN_admin)
                            .addComponent(payableListY_admin)
                            .addComponent(payableListN_admin)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminLabel08)
                                    .addComponent(adminLabel14))))
                        .addGap(20, 20, 20)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productY_admin)
                            .addComponent(productN_admin)
                            .addComponent(assetY_admin)
                            .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(assetN_admin)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(salesY_admin)
                                .addComponent(salesN_admin))
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminLabel09)
                                    .addComponent(adminLabel15)))))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profitY_admin)
                            .addComponent(profitN_admin))
                        .addGap(52, 52, 52)))
                .addGap(20, 20, 20)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminLabel20)
                    .addComponent(note_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profitY_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitY_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profitY_adminActionPerformed

    private void employeeNum_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNum_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNum_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton achievementN_admin;
    private javax.swing.JRadioButton achievementY_admin;
    private javax.swing.ButtonGroup achievement_admin;
    private javax.swing.JLabel adminLabel01;
    private javax.swing.JLabel adminLabel02;
    private javax.swing.JLabel adminLabel03;
    private javax.swing.JLabel adminLabel04;
    private javax.swing.JLabel adminLabel05;
    private javax.swing.JLabel adminLabel06;
    private javax.swing.JLabel adminLabel07;
    private javax.swing.JLabel adminLabel08;
    private javax.swing.JLabel adminLabel09;
    private javax.swing.JLabel adminLabel10;
    private javax.swing.JLabel adminLabel11;
    private javax.swing.JLabel adminLabel12;
    private javax.swing.JLabel adminLabel13;
    private javax.swing.JLabel adminLabel14;
    private javax.swing.JLabel adminLabel15;
    private javax.swing.JLabel adminLabel16;
    private javax.swing.JLabel adminLabel17;
    private javax.swing.JLabel adminLabel18;
    private javax.swing.JLabel adminLabel19;
    private javax.swing.JLabel adminLabel20;
    private javax.swing.ButtonGroup adminList_admin;
    private javax.swing.JRadioButton adminN_admin;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JRadioButton adminY_admin;
    private javax.swing.JRadioButton assetN_admin;
    private javax.swing.JRadioButton assetY_admin;
    private javax.swing.ButtonGroup asset_admin;
    private javax.swing.JRadioButton attendanceN_admin;
    private javax.swing.JRadioButton attendanceY_admin;
    private javax.swing.ButtonGroup attendance_admin;
    private javax.swing.JRadioButton billboardN_admin;
    private javax.swing.JRadioButton billboardY_admin;
    private javax.swing.ButtonGroup billboard_admin;
    private javax.swing.JLabel empDepat_admin;
    private javax.swing.JLabel empPasswd_admin;
    private javax.swing.JRadioButton employeeN_admin;
    private javax.swing.JLabel employeeName_admin;
    private javax.swing.JComboBox<String> employeeNum_admin;
    private javax.swing.JRadioButton employeeY_admin;
    private javax.swing.ButtonGroup employee_admin;
    private javax.swing.JRadioButton issueN_admin;
    private javax.swing.JRadioButton issueY_admin;
    private javax.swing.ButtonGroup issue_admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton materialN_admin;
    private javax.swing.JRadioButton materialY_admin;
    private javax.swing.ButtonGroup material_admin;
    private javax.swing.JRadioButton memberN_admin;
    private javax.swing.JRadioButton memberY_admin;
    private javax.swing.ButtonGroup member_admin;
    private javax.swing.JTextField note_admin;
    private javax.swing.JRadioButton orderItemN_admin;
    private javax.swing.JRadioButton orderItemY_admin;
    private javax.swing.ButtonGroup orderItem_admin;
    private javax.swing.JRadioButton orderListN_admin;
    private javax.swing.JRadioButton orderListY_admin;
    private javax.swing.ButtonGroup orderList_admin;
    private javax.swing.JRadioButton payRollN_admin;
    private javax.swing.JRadioButton payRollY_admin;
    private javax.swing.ButtonGroup payRoll_admin;
    private javax.swing.JRadioButton payableListN_admin;
    private javax.swing.JRadioButton payableListY_admin;
    private javax.swing.ButtonGroup payableList_admin;
    private javax.swing.JRadioButton productN_admin;
    private javax.swing.JRadioButton productY_admin;
    private javax.swing.ButtonGroup product_admin;
    private javax.swing.JRadioButton profitN_admin;
    private javax.swing.JRadioButton profitY_admin;
    private javax.swing.ButtonGroup profit_admin;
    private javax.swing.JRadioButton purchaseN_admin;
    private javax.swing.JRadioButton purchaseY_admin;
    private javax.swing.ButtonGroup purchase_admin;
    private javax.swing.JRadioButton salesN_admin;
    private javax.swing.JRadioButton salesY_admin;
    private javax.swing.ButtonGroup sales_admin;
    private javax.swing.JRadioButton vendorN_admin;
    private javax.swing.JRadioButton vendorY_admin;
    private javax.swing.ButtonGroup vendor_admin;
    // End of variables declaration//GEN-END:variables
}
