/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class asset extends javax.swing.JFrame {

    /**
     * Creates new form asset
     */
    public asset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assetPanel = new javax.swing.JPanel();
        assetLabel01 = new javax.swing.JLabel();
        assetLabel02 = new javax.swing.JLabel();
        assetLabel03 = new javax.swing.JLabel();
        assetLabel04 = new javax.swing.JLabel();
        buyDate_asset = new com.toedter.calendar.JDateChooser();
        assetLabel05 = new javax.swing.JLabel();
        assetLabel06 = new javax.swing.JLabel();
        value_asset = new javax.swing.JTextField();
        assetLabel07 = new javax.swing.JLabel();
        lifespan_asset = new javax.swing.JTextField();
        assetLabel08 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        note_asset = new javax.swing.JTextArea();
        id_asset = new javax.swing.JLabel();
        department_asset = new javax.swing.JComboBox<>();
        assetName_asset = new javax.swing.JTextField();
        qty_asset = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 470));
        setPreferredSize(new java.awt.Dimension(980, 470));

        assetPanel.setMinimumSize(new java.awt.Dimension(980, 470));

        assetLabel01.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetLabel01.setText("資產編號");

        assetLabel02.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetLabel02.setText("資產名稱");

        assetLabel03.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetLabel03.setText("採購日期");

        assetLabel04.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetLabel04.setText("使用部門");

        buyDate_asset.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        assetLabel05.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetLabel05.setText("數量");

        assetLabel06.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetLabel06.setText("購入金額");
        assetLabel06.setToolTipText("");

        value_asset.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        assetLabel07.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetLabel07.setText("折舊年限");

        lifespan_asset.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        lifespan_asset.setMinimumSize(new java.awt.Dimension(6, 30));
        lifespan_asset.setPreferredSize(new java.awt.Dimension(6, 30));

        assetLabel08.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetLabel08.setText("其它備註");

        note_asset.setColumns(20);
        note_asset.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        note_asset.setRows(5);
        jScrollPane4.setViewportView(note_asset);

        id_asset.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        id_asset.setText("系統自動產生");

        department_asset.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        department_asset.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        department_asset.setMinimumSize(new java.awt.Dimension(73, 30));
        department_asset.setPreferredSize(new java.awt.Dimension(73, 30));

        assetName_asset.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        qty_asset.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        javax.swing.GroupLayout assetPanelLayout = new javax.swing.GroupLayout(assetPanel);
        assetPanel.setLayout(assetPanelLayout);
        assetPanelLayout.setHorizontalGroup(
            assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assetPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assetLabel03)
                    .addComponent(assetLabel02)
                    .addComponent(assetLabel04)
                    .addComponent(assetLabel01))
                .addGap(18, 18, 18)
                .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(assetName_asset, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buyDate_asset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(department_asset, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(id_asset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assetPanelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assetLabel06, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(assetLabel07)
                            .addComponent(assetLabel05))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assetPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(assetLabel08)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lifespan_asset, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(value_asset, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(qty_asset, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        assetPanelLayout.setVerticalGroup(
            assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assetPanelLayout.createSequentialGroup()
                        .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assetLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_asset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assetLabel02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(value_asset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assetName_asset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assetLabel06, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assetLabel03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyDate_asset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(assetPanelLayout.createSequentialGroup()
                        .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assetLabel05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qty_asset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lifespan_asset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assetLabel07, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assetLabel04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(assetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(department_asset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(assetLabel08, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(21, Short.MAX_VALUE)
                    .addComponent(assetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new asset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assetLabel01;
    private javax.swing.JLabel assetLabel02;
    private javax.swing.JLabel assetLabel03;
    private javax.swing.JLabel assetLabel04;
    private javax.swing.JLabel assetLabel05;
    private javax.swing.JLabel assetLabel06;
    private javax.swing.JLabel assetLabel07;
    private javax.swing.JLabel assetLabel08;
    private javax.swing.JTextField assetName_asset;
    private javax.swing.JPanel assetPanel;
    private com.toedter.calendar.JDateChooser buyDate_asset;
    private javax.swing.JComboBox<String> department_asset;
    private javax.swing.JLabel id_asset;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lifespan_asset;
    private javax.swing.JTextArea note_asset;
    private javax.swing.JTextField qty_asset;
    private javax.swing.JTextField value_asset;
    // End of variables declaration//GEN-END:variables
}
