/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class billboard extends javax.swing.JFrame {

    /**
     * Creates new form billboard
     */
    public billboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billboardPanel = new javax.swing.JPanel();
        billboardLabel01 = new javax.swing.JLabel();
        billboardLabel02 = new javax.swing.JLabel();
        billboardLabel03 = new javax.swing.JLabel();
        issueDate_billboard = new com.toedter.calendar.JDateChooser();
        billboardLabel04 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        announce_billboard = new javax.swing.JTextArea();
        id_billboard = new javax.swing.JLabel();
        employeeNum_billboard = new javax.swing.JComboBox<>();
        billboardLabel05 = new javax.swing.JLabel();
        deadline_billboard = new com.toedter.calendar.JDateChooser();
        billboardLabel06 = new javax.swing.JLabel();
        remark_billboard = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        employeeName_billboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 470));
        setResizable(false);

        billboardPanel.setMinimumSize(new java.awt.Dimension(980, 470));

        billboardLabel01.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardLabel01.setText("公告編號");

        billboardLabel02.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardLabel02.setText("公告日期");

        billboardLabel03.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardLabel03.setText("公告維護者");

        issueDate_billboard.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        billboardLabel04.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardLabel04.setText("公告內容");

        announce_billboard.setColumns(20);
        announce_billboard.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        announce_billboard.setRows(5);
        jScrollPane4.setViewportView(announce_billboard);

        id_billboard.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        id_billboard.setText("系統自動產生");

        employeeNum_billboard.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeNum_billboard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employeeNum_billboard.setMinimumSize(new java.awt.Dimension(73, 30));
        employeeNum_billboard.setPreferredSize(new java.awt.Dimension(73, 30));

        billboardLabel05.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardLabel05.setText("有效日期");

        deadline_billboard.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        billboardLabel06.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        billboardLabel06.setText("備註");

        remark_billboard.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N

        employeeName_billboard.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employeeName_billboard.setText("員工名");

        javax.swing.GroupLayout billboardPanelLayout = new javax.swing.GroupLayout(billboardPanel);
        billboardPanel.setLayout(billboardPanelLayout);
        billboardPanelLayout.setHorizontalGroup(
            billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billboardPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(billboardPanelLayout.createSequentialGroup()
                        .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billboardLabel04)
                            .addGroup(billboardPanelLayout.createSequentialGroup()
                                .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(billboardLabel02)
                                    .addComponent(billboardLabel03)
                                    .addComponent(billboardLabel01))
                                .addGap(18, 18, 18)
                                .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(issueDate_billboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id_billboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(employeeNum_billboard, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeName_billboard, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(billboardLabel05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(billboardLabel06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remark_billboard)
                            .addComponent(deadline_billboard, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)))
                    .addComponent(jSeparator1))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        billboardPanelLayout.setVerticalGroup(
            billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billboardPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billboardLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_billboard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billboardPanelLayout.createSequentialGroup()
                        .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billboardLabel02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issueDate_billboard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billboardLabel05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(billboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billboardLabel03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeNum_billboard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billboardLabel06)
                            .addComponent(remark_billboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeName_billboard)))
                    .addComponent(deadline_billboard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billboardLabel04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea announce_billboard;
    private javax.swing.JLabel billboardLabel01;
    private javax.swing.JLabel billboardLabel02;
    private javax.swing.JLabel billboardLabel03;
    private javax.swing.JLabel billboardLabel04;
    private javax.swing.JLabel billboardLabel05;
    private javax.swing.JLabel billboardLabel06;
    private javax.swing.JPanel billboardPanel;
    private com.toedter.calendar.JDateChooser deadline_billboard;
    private javax.swing.JLabel employeeName_billboard;
    private javax.swing.JComboBox<String> employeeNum_billboard;
    private javax.swing.JLabel id_billboard;
    private com.toedter.calendar.JDateChooser issueDate_billboard;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField remark_billboard;
    // End of variables declaration//GEN-END:variables
}
