/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class department extends javax.swing.JPanel {

    /**
     * Creates new form department
     */
    public department() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assetLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id_department = new javax.swing.JLabel();
        depName_department = new javax.swing.JTextField();

        setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assetLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        assetLabel2.setText("部門ID");
        add(assetLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 30));

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel1.setText("部門名稱");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 25));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 191, -1, -1));

        id_department.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        id_department.setText("generated by system...");
        add(id_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 269, 30));

        depName_department.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        add(depName_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 188, 269, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assetLabel2;
    private javax.swing.JTextField depName_department;
    private javax.swing.JLabel id_department;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
