/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class department extends javax.swing.JPanel {

    /**
     * Creates new form department
     */
    public department() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depLabel1 = new javax.swing.JLabel();
        depLabel2 = new javax.swing.JLabel();
        id_department = new javax.swing.JLabel();
        depName_department = new javax.swing.JTextField();
        depLabel3 = new javax.swing.JLabel();
        title_department = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        note_department = new javax.swing.JTextArea();

        setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        setMaximumSize(new java.awt.Dimension(980, 470));
        setMinimumSize(new java.awt.Dimension(980, 470));
        setPreferredSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        depLabel1.setText("部門ID");
        add(depLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 30));

        depLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        depLabel2.setText("部門名稱");
        depLabel2.setMaximumSize(new java.awt.Dimension(75, 25));
        depLabel2.setMinimumSize(new java.awt.Dimension(75, 25));
        depLabel2.setPreferredSize(new java.awt.Dimension(75, 25));
        add(depLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        id_department.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(id_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 269, 30));

        depName_department.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(depName_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 269, -1));

        depLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        depLabel3.setText("職銜");
        add(depLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 296, -1, -1));

        title_department.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(title_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 293, 269, -1));

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel1.setText("備註");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 197, -1, -1));

        note_department.setColumns(20);
        note_department.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        note_department.setRows(5);
        jScrollPane1.setViewportView(note_department);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 197, 370, 123));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel depLabel1;
    private javax.swing.JLabel depLabel2;
    private javax.swing.JLabel depLabel3;
    private javax.swing.JTextField depName_department;
    private javax.swing.JLabel id_department;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea note_department;
    private javax.swing.JTextField title_department;
    // End of variables declaration//GEN-END:variables
}
