/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fox70
 */
public class Employee extends javax.swing.JPanel {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        dateBirthday = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbPosition = new javax.swing.JComboBox<>();
        cbDepartment = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JEditorPane();
        lbEmployeeNum = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(980, 470));
        setMinimumSize(new java.awt.Dimension(980, 470));
        setPreferredSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel1.setText("員工編號");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 66, -1, -1));

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel2.setText("姓名");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel3.setText("住址");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel4.setText("電話");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel5.setText("性別");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtTel.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 225, -1));

        txtName.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 225, -1));

        txtAddress.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 225, -1));

        bgGender.add(rbMale);
        rbMale.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        rbMale.setText("男");
        add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        bgGender.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        rbFemale.setText("女");
        add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel6.setText("出生年月日");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 62, -1, -1));

        dateBirthday.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(dateBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 62, 274, -1));

        jLabel7.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel8.setText("部門");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel9.setText("職等");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel10.setText("備註");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        cbPosition.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(cbPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 274, -1));

        cbDepartment.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "　　", " " }));
        cbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartmentActionPerformed(evt);
            }
        });
        add(cbDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 274, -1));

        txtNote.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(txtNote);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 274, 110));

        lbEmployeeNum.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(lbEmployeeNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 62, 225, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void cbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepartmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGender;
    private javax.swing.JComboBox<String> cbDepartment;
    private javax.swing.JComboBox<String> cbPosition;
    private com.toedter.calendar.JDateChooser dateBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmployeeNum;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JEditorPane txtNote;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
