
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.LinkedList;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 許哲浩
 */
public class issue extends javax.swing.JPanel {
    private Connection conn;
    /**
     * Creates new form orderList
     */
    public static void main(String[] args){
        issue issue = new issue();
        issue.setVisible(true);
    }
    public issue() {
        initComponents();
        init();
        
    }
    private void init(){ 
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=erp;user=sa;password=00000000;");
            
            System.out.println("conn OK");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    protected void insert(){
        try{
            PreparedStatement pstmt = conn.prepareStatement(
                    "INSERT INTO issue(customerId,complaint,price,note) VALUES('"
                            + ""+text_customerId.getText()+"','"
                            + ""+text_complaint.getText()+"','"
                            + ""+text_price.getText()+"','"
                            + ""+text_note.getText()+"')");
            pstmt.executeUpdate();
            
           textClear();
            
            pstmt.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    protected LinkedList select(){
        try{
            PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM issue");
            ResultSet result =  pstmt.executeQuery();
            
            
            LinkedList<String[]> rows = new LinkedList<String[]>();
            
            while(result.next()){
                String[] row = new String[4];
                row[0] = result.getString("customerId");
                row[1] = result.getString("complaint");
                row[2] = result.getString("price");
                row[3] = result.getString("note");

                rows.add(row);
            }

            pstmt.close();
            return rows;
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }
    protected String[] getColumn(){ 
        String[] columnName = new String[]{"customerId","complaint","price","note",};
        return columnName;
    }
    
    private void textClear(){
        text_customerId.setText("");
        text_complaint.setText("");
        text_price.setText("");
        text_note.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_customerId = new javax.swing.JLabel();
        label_price = new javax.swing.JLabel();
        label_complaint = new javax.swing.JLabel();
        label_note = new javax.swing.JLabel();
        text_customerId = new javax.swing.JTextField();
        text_price = new javax.swing.JTextField();
        scroll_complaint = new javax.swing.JScrollPane();
        text_complaint = new javax.swing.JTextArea();
        scroll_note = new javax.swing.JScrollPane();
        text_note = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(980, 470));
        setPreferredSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_customerId.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_customerId.setText("客戶編號");
        add(label_customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        label_price.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_price.setText("金額");
        add(label_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        label_complaint.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_complaint.setText("客訴內容");
        add(label_complaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        label_note.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_note.setText("備註");
        add(label_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        text_customerId.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 150, 25));

        text_price.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 150, 25));

        text_complaint.setColumns(20);
        text_complaint.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_complaint.setRows(5);
        scroll_complaint.setViewportView(text_complaint);

        add(scroll_complaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 600, -1));

        scroll_note.setToolTipText("");

        text_note.setColumns(20);
        text_note.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_note.setRows(5);
        scroll_note.setViewportView(text_note);

        add(scroll_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_complaint;
    private javax.swing.JLabel label_customerId;
    private javax.swing.JLabel label_note;
    private javax.swing.JLabel label_price;
    private javax.swing.JScrollPane scroll_complaint;
    private javax.swing.JScrollPane scroll_note;
    private javax.swing.JTextArea text_complaint;
    private javax.swing.JTextField text_customerId;
    private javax.swing.JTextArea text_note;
    private javax.swing.JTextField text_price;
    // End of variables declaration//GEN-END:variables
}
