
import java.awt.Toolkit;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        init();
    }
    
     private void init(){
        setResizable(false);
        setLocationRelativeTo(null);//置中
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/drink.png")));
        setTitle("---ERP LOGIN---");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_P = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon("login_BG.jpg");
                Image i = im.getImage();
                g.drawImage(i,0, 0, this.getSize().width, this.getSize().height, this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        loginLabel02 = new javax.swing.JLabel();
        loginLabel01 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        employID_login = new javax.swing.JTextField();
        employPW_login = new javax.swing.JTextField();
        loginLabel03 = new javax.swing.JLabel();
        employPwEdit_login = new javax.swing.JTextField();
        login_log = new javax.swing.JButton();
        showResult_login = new javax.swing.JLabel();
        onduty_log = new javax.swing.JButton();
        offduty_log = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_P.setBackground(new java.awt.Color(0, 153, 102));
        login_P.setMaximumSize(new java.awt.Dimension(650, 500));
        login_P.setMinimumSize(new java.awt.Dimension(650, 500));
        login_P.setOpaque(false);
        login_P.setPreferredSize(new java.awt.Dimension(650, 500));
        login_P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(131, 62, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ERP / 打卡系統");
        login_P.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 16, 325, 82));

        loginLabel02.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        loginLabel02.setText("密碼");
        login_P.add(loginLabel02, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 206, 122, 53));

        loginLabel01.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        loginLabel01.setText("員工編號");
        login_P.add(loginLabel01, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 135, 122, 53));
        login_P.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 107, 516, 10));
        login_P.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 277, 516, 10));

        employID_login.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        employID_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employID_loginMouseClicked(evt);
            }
        });
        login_P.add(employID_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 135, 320, 53));

        employPW_login.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        login_P.add(employPW_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 206, 320, 53));

        loginLabel03.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        loginLabel03.setText("修改密碼");
        login_P.add(loginLabel03, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 296, 122, 53));

        employPwEdit_login.setFont(new java.awt.Font("微軟正黑體", 0, 16)); // NOI18N
        employPwEdit_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employPwEdit_loginMouseClicked(evt);
            }
        });
        login_P.add(employPwEdit_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 297, 320, 53));

        login_log.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        login_log.setForeground(new java.awt.Color(0, 0, 204));
        login_log.setText("登入");
        login_log.setMinimumSize(new java.awt.Dimension(90, 30));
        login_log.setPreferredSize(new java.awt.Dimension(90, 30));
        login_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_logActionPerformed(evt);
            }
        });
        login_P.add(login_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 424, 152, 47));

        showResult_login.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        showResult_login.setForeground(new java.awt.Color(255, 51, 51));
        showResult_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_P.add(showResult_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 359, 620, 47));

        onduty_log.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        onduty_log.setForeground(new java.awt.Color(102, 0, 102));
        onduty_log.setText("上班打卡");
        onduty_log.setMaximumSize(new java.awt.Dimension(90, 30));
        onduty_log.setPreferredSize(new java.awt.Dimension(69, 33));
        onduty_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onduty_logActionPerformed(evt);
            }
        });
        login_P.add(onduty_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 424, 131, 47));

        offduty_log.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        offduty_log.setForeground(new java.awt.Color(102, 0, 102));
        offduty_log.setText("下班打卡");
        offduty_log.setMaximumSize(new java.awt.Dimension(90, 30));
        offduty_log.setMinimumSize(new java.awt.Dimension(90, 30));
        offduty_log.setPreferredSize(new java.awt.Dimension(90, 30));
        offduty_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offduty_logActionPerformed(evt);
            }
        });
        login_P.add(offduty_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 424, 128, 47));

        getContentPane().add(login_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_logActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_logActionPerformed

    private void onduty_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onduty_logActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onduty_logActionPerformed

    private void offduty_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offduty_logActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offduty_logActionPerformed

    private void employPwEdit_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employPwEdit_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_employPwEdit_loginMouseClicked

    private void employID_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employID_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_employID_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField employID_login;
    private javax.swing.JTextField employPW_login;
    private javax.swing.JTextField employPwEdit_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginLabel01;
    private javax.swing.JLabel loginLabel02;
    private javax.swing.JLabel loginLabel03;
    private javax.swing.JPanel login_P;
    private javax.swing.JButton login_log;
    private javax.swing.JButton offduty_log;
    private javax.swing.JButton onduty_log;
    private javax.swing.JLabel showResult_login;
    // End of variables declaration//GEN-END:variables
}
