/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class member1 extends javax.swing.JPanel {

    /**
     * Creates new form member
     */
    public member1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_member = new javax.swing.ButtonGroup();
        label_customerId = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        label_memberName = new javax.swing.JLabel();
        label_note = new javax.swing.JLabel();
        label_tel = new javax.swing.JLabel();
        label_gender = new javax.swing.JLabel();
        label_address = new javax.swing.JLabel();
        text_customerId = new javax.swing.JTextField();
        text_password = new javax.swing.JTextField();
        text_memberName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_note = new javax.swing.JTextArea();
        text_tel = new javax.swing.JTextField();
        radio_male = new javax.swing.JRadioButton();
        radio_female = new javax.swing.JRadioButton();
        text_address = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(980, 470));
        setMinimumSize(new java.awt.Dimension(980, 470));
        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_customerId.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_customerId.setText("客戶編號");
        add(label_customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 63, -1, -1));

        label_password.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_password.setText("客戶密碼");
        add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 141, -1, -1));

        label_memberName.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_memberName.setText("客戶名稱");
        add(label_memberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 219, -1, -1));

        label_note.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_note.setText("備註");
        add(label_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 293, 60, -1));

        label_tel.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_tel.setText("電話");
        add(label_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 63, 60, -1));

        label_gender.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_gender.setText("性別");
        add(label_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 141, 60, -1));

        label_address.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_address.setText("地址");
        add(label_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 219, 60, -1));

        text_customerId.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(text_customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 60, 210, -1));

        text_password.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 138, 210, -1));

        text_memberName.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(text_memberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 216, 210, -1));

        text_note.setColumns(20);
        text_note.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_note.setRows(5);
        jScrollPane1.setViewportView(text_note);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 293, 687, -1));

        text_tel.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        text_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_telKeyTyped(evt);
            }
        });
        add(text_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 60, 250, -1));

        gender_member.add(radio_male);
        radio_male.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        radio_male.setText("男");
        add(radio_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 137, 98, -1));

        gender_member.add(radio_female);
        radio_female.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        radio_female.setText("女");
        add(radio_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 137, 83, -1));

        text_address.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(text_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 216, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void text_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_telKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_telKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gender_member;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_customerId;
    private javax.swing.JLabel label_gender;
    private javax.swing.JLabel label_memberName;
    private javax.swing.JLabel label_note;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_tel;
    private javax.swing.JRadioButton radio_female;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JTextField text_address;
    private javax.swing.JTextField text_customerId;
    private javax.swing.JTextField text_memberName;
    private javax.swing.JTextArea text_note;
    private javax.swing.JTextField text_password;
    private javax.swing.JTextField text_tel;
    // End of variables declaration//GEN-END:variables
}
