
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.LinkedList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 許哲浩
 */
public class orderItem extends javax.swing.JPanel {
    private Connection conn;
    /**
     * Creates new form orderList
     */
    public orderItem() {
        initComponents();
        init();
    }
    
    private void init(){ 
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=erp;user=sa;password=00000000;");
            
            System.out.println("conn OK");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
        
    protected void insert(){
        try{
            PreparedStatement pstmt = conn.prepareStatement(
                    "INSERT INTO orderitem(orderNum,productNum,qty,note) VALUES('"
                            + ""+text_orderNum.getText()+"','"
                            + ""+text_productNum.getText()+"','"
                            + ""+text_qty.getText()+"','"
                            + ""+text_note.getText()+"')");
            pstmt.executeUpdate();
            
           textClear();
            
            pstmt.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    protected LinkedList select(){
        try{
            PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM orderitem");
            ResultSet result =  pstmt.executeQuery();
            
            
            LinkedList<String[]> rows = new LinkedList<String[]>();
            
            while(result.next()){
                String[] row = new String[4];
                row[0] = result.getString("orderNum");
                row[1] = result.getString("productNum");
                row[2] = result.getString("qty");
                row[3] = result.getString("note");

                rows.add(row);
            }

            pstmt.close();
            return rows;
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }
    protected String[] getColumn(){ 
        String[] columnName = 
                new String[]{"orderNum","productNum","qty","note"};
        return columnName;
    }
    
    private void textClear(){
        text_orderNum.setText("");
        text_productNum.setText("");
        text_qty.setText("");      
        text_note.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_orderNum = new javax.swing.JLabel();
        label_productNum = new javax.swing.JLabel();
        label_qty = new javax.swing.JLabel();
        label_note = new javax.swing.JLabel();
        text_orderNum = new javax.swing.JTextField();
        text_productNum = new javax.swing.JTextField();
        text_qty = new javax.swing.JTextField();
        scroll_note = new javax.swing.JScrollPane();
        text_note = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(980, 470));
        setPreferredSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_orderNum.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_orderNum.setText("訂單編號");
        add(label_orderNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        label_productNum.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_productNum.setText("產品編號");
        add(label_productNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        label_qty.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_qty.setText("數量");
        add(label_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        label_note.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_note.setText("備註");
        add(label_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        text_orderNum.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_orderNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 150, 25));

        text_productNum.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_productNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 150, 25));

        text_qty.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 150, 25));

        text_note.setColumns(20);
        text_note.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_note.setRows(5);
        scroll_note.setViewportView(text_note);

        add(scroll_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_note;
    private javax.swing.JLabel label_orderNum;
    private javax.swing.JLabel label_productNum;
    private javax.swing.JLabel label_qty;
    private javax.swing.JScrollPane scroll_note;
    private javax.swing.JTextArea text_note;
    private javax.swing.JTextField text_orderNum;
    private javax.swing.JTextField text_productNum;
    private javax.swing.JTextField text_qty;
    // End of variables declaration//GEN-END:variables
}
