
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.LinkedList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 許哲浩
 */
public class orderList extends javax.swing.JPanel {
    private Connection conn;
    /**
     * Creates new form orderList
     */
    public orderList() {
        initComponents();
        init();
    }
    
    private void init(){ 
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=erp;user=sa;password=00000000;");
            
            System.out.println("conn OK");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    protected void insert(){
        //須set JDateChoose的Format才能直接用
        java.util.Date date = date_orderDate.getDate();        
        String strDate = java.text.DateFormat.getDateInstance().format(date);      
        System.out.println(strDate);
        PreparedStatement pstmt;
        try{
            pstmt = conn.prepareStatement(
                    "INSERT INTO orderlist(orderNum,customerId,orderDate,status,dispatch,note) VALUES('"
                            + ""+text_orderNum.getText()+"','"
                            + ""+text_customerId.getText()+"','"
                            + ""+strDate+"','"
                            + ""+text_status.getText()+"','"
                            + ""+text_dispatch.getText()+"','"
                            + ""+text_note.getText()+"')");
            pstmt.executeUpdate();
            
           textClear();
            
            pstmt.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    protected LinkedList select(){
        try{
            PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM orderlist");
            ResultSet result =  pstmt.executeQuery();
            
            
            LinkedList<String[]> rows = new LinkedList<String[]>();
            
            while(result.next()){
                String[] row = new String[6];
                row[0] = result.getString("orderNum");
                row[1] = result.getString("customerId");
                row[2] = result.getString("orderDate");
                row[3] = result.getString("status");
                row[4] = result.getString("dispatch");
                row[5] = result.getString("note");

                rows.add(row);
            }

            pstmt.close();
            return rows;
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }
    protected String[] getColumn(){ 
        String[] columnName = 
                new String[]{"orderNum","customerId","orderDate","status","dispatch","note"};
        return columnName;
    }
    
    private void textClear(){
        text_orderNum.setText("");
        text_customerId.setText("");
        date_orderDate.setDate(null);
        text_status.setText("");
        text_dispatch.setText("");        
        text_note.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_orderNum = new javax.swing.JLabel();
        label_customerId = new javax.swing.JLabel();
        label_orderDate = new javax.swing.JLabel();
        label_status = new javax.swing.JLabel();
        label_dispatch = new javax.swing.JLabel();
        label_note = new javax.swing.JLabel();
        text_orderNum = new javax.swing.JTextField();
        text_status = new javax.swing.JTextField();
        text_dispatch = new javax.swing.JTextField();
        text_customerId = new javax.swing.JTextField();
        date_orderDate = new com.toedter.calendar.JDateChooser();
        scroll_note = new javax.swing.JScrollPane();
        text_note = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(980, 470));
        setPreferredSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_orderNum.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_orderNum.setText("訂單編號");
        add(label_orderNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        label_customerId.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_customerId.setText("客戶編號");
        add(label_customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        label_orderDate.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_orderDate.setText("下單日期");
        add(label_orderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 20));

        label_status.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_status.setText("狀態");
        add(label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        label_dispatch.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_dispatch.setText("配送方式");
        add(label_dispatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        label_note.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        label_note.setText("備註");
        add(label_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        text_orderNum.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_orderNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 150, 25));

        text_status.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 150, 25));

        text_dispatch.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_dispatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 150, 25));

        text_customerId.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 150, 25));

        date_orderDate.setDateFormatString("yyyy/M/d h:m:s");
        add(date_orderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 180, 25));

        text_note.setColumns(20);
        text_note.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_note.setRows(5);
        scroll_note.setViewportView(text_note);

        add(scroll_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date_orderDate;
    private javax.swing.JLabel label_customerId;
    private javax.swing.JLabel label_dispatch;
    private javax.swing.JLabel label_note;
    private javax.swing.JLabel label_orderDate;
    private javax.swing.JLabel label_orderNum;
    private javax.swing.JLabel label_status;
    private javax.swing.JScrollPane scroll_note;
    private javax.swing.JTextField text_customerId;
    private javax.swing.JTextField text_dispatch;
    private javax.swing.JTextArea text_note;
    private javax.swing.JTextField text_orderNum;
    private javax.swing.JTextField text_status;
    // End of variables declaration//GEN-END:variables
}
