/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class payableList extends javax.swing.JFrame {

    /**
     * Creates new form payableList
     */
    public payableList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payableListPanel = new javax.swing.JPanel();
        purchaseLabel01 = new javax.swing.JLabel();
        vendorNum_Accn = new javax.swing.JTextField();
        purchaseLabel02 = new javax.swing.JLabel();
        purchaseLabel03 = new javax.swing.JLabel();
        purchaseLabel04 = new javax.swing.JLabel();
        com.toedter.calendar.JDateChooser transactionDate_Accn = new com.toedter.calendar.JDateChooser();
        purchaseLabel05 = new javax.swing.JLabel();
        purchaseLabel06 = new javax.swing.JLabel();
        amount_Accn = new javax.swing.JTextField();
        purchaseLabel07 = new javax.swing.JLabel();
        actualPayAmount_Accn = new javax.swing.JTextField();
        purchaseLabel08 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        note_Accn = new javax.swing.JTextArea();
        purchaseNum_Accn = new javax.swing.JComboBox<>();
        payDue_Accn = new com.toedter.calendar.JDateChooser();
        payDate_Accn = new com.toedter.calendar.JDateChooser();
        purchaseLabel8 = new javax.swing.JLabel();
        purchaseLabel9 = new javax.swing.JLabel();
        discount_Accn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ifClose_Accn = new javax.swing.JLabel();
        vendorName_Accn = new javax.swing.JLabel();
        payWith_Accn = new javax.swing.JComboBox<>();
        payableListID_Accn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        payableListPanel.setMinimumSize(new java.awt.Dimension(980, 470));
        payableListPanel.setPreferredSize(new java.awt.Dimension(980, 470));

        purchaseLabel01.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel01.setText("廠商編號");

        vendorNum_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        vendorNum_Accn.setPreferredSize(new java.awt.Dimension(10, 26));

        purchaseLabel02.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel02.setText("進貨單號");

        purchaseLabel03.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel03.setText("交易日期");

        purchaseLabel04.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel04.setText("應付日期");

        transactionDate_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        transactionDate_Accn.setPreferredSize(new java.awt.Dimension(92, 30));

        purchaseLabel05.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel05.setText("沖帳日期");

        purchaseLabel06.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel06.setText("應付金額");
        purchaseLabel06.setToolTipText("");

        amount_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        purchaseLabel07.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel07.setText("沖帳金額");

        actualPayAmount_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        purchaseLabel08.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel08.setText("備註");

        note_Accn.setColumns(20);
        note_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        note_Accn.setRows(5);
        jScrollPane4.setViewportView(note_Accn);

        purchaseNum_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        purchaseNum_Accn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        payDue_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        payDue_Accn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payDue_AccnMouseClicked(evt);
            }
        });

        payDate_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        purchaseLabel8.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel8.setText("付款方式");

        purchaseLabel9.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel9.setText("沖帳折讓金額");

        discount_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel1.setText("結案Y/N");

        ifClose_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        ifClose_Accn.setForeground(new java.awt.Color(255, 51, 51));
        ifClose_Accn.setText("結案預設N");

        vendorName_Accn.setText("廠商名稱");

        payWith_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        payWith_Accn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        payWith_Accn.setMinimumSize(new java.awt.Dimension(73, 30));
        payWith_Accn.setPreferredSize(new java.awt.Dimension(73, 30));

        payableListID_Accn.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        payableListID_Accn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        payableListID_Accn.setText("應付帳款單號");

        javax.swing.GroupLayout payableListPanelLayout = new javax.swing.GroupLayout(payableListPanel);
        payableListPanel.setLayout(payableListPanelLayout);
        payableListPanelLayout.setHorizontalGroup(
            payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payableListPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(purchaseLabel03)
                            .addComponent(purchaseLabel02)
                            .addComponent(purchaseLabel04)
                            .addComponent(purchaseLabel01))
                        .addComponent(purchaseLabel06)))
                .addGap(18, 18, 18)
                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(transactionDate_Accn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(purchaseNum_Accn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payDue_Accn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amount_Accn)
                    .addComponent(vendorNum_Accn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ifClose_Accn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendorName_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payableListPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(purchaseLabel07)
                            .addComponent(purchaseLabel05)
                            .addComponent(purchaseLabel9)))
                    .addComponent(purchaseLabel8)
                    .addComponent(purchaseLabel08, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payableListPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payableListPanelLayout.createSequentialGroup()
                        .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(payWith_Accn, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(payDate_Accn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(actualPayAmount_Accn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discount_Accn, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(150, 150, 150))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payableListPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payableListID_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        payableListPanelLayout.setVerticalGroup(
            payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payableListPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(payableListID_Accn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payableListPanelLayout.createSequentialGroup()
                        .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purchaseLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vendorNum_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vendorName_Accn))
                        .addGap(35, 35, 35)
                        .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purchaseLabel02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purchaseNum_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purchaseLabel07, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualPayAmount_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(purchaseLabel05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payDate_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purchaseLabel03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactionDate_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(purchaseLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(discount_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payableListPanelLayout.createSequentialGroup()
                        .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(payableListPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(purchaseLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(payWith_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addComponent(purchaseLabel08, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(payableListPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(purchaseLabel04, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(payDue_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(amount_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purchaseLabel06, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23)
                        .addGroup(payableListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ifClose_Accn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payableListPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(payableListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(payableListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payDue_AccnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payDue_AccnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_payDue_AccnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payableList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payableList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualPayAmount_Accn;
    private javax.swing.JTextField amount_Accn;
    private javax.swing.JTextField discount_Accn;
    private javax.swing.JLabel ifClose_Accn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea note_Accn;
    private com.toedter.calendar.JDateChooser payDate_Accn;
    private com.toedter.calendar.JDateChooser payDue_Accn;
    private javax.swing.JComboBox<String> payWith_Accn;
    private javax.swing.JLabel payableListID_Accn;
    private javax.swing.JPanel payableListPanel;
    private javax.swing.JLabel purchaseLabel01;
    private javax.swing.JLabel purchaseLabel02;
    private javax.swing.JLabel purchaseLabel03;
    private javax.swing.JLabel purchaseLabel04;
    private javax.swing.JLabel purchaseLabel05;
    private javax.swing.JLabel purchaseLabel06;
    private javax.swing.JLabel purchaseLabel07;
    private javax.swing.JLabel purchaseLabel08;
    private javax.swing.JLabel purchaseLabel8;
    private javax.swing.JLabel purchaseLabel9;
    private javax.swing.JComboBox<String> purchaseNum_Accn;
    private javax.swing.JLabel vendorName_Accn;
    private javax.swing.JTextField vendorNum_Accn;
    // End of variables declaration//GEN-END:variables
}
