/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fox70
 */
public class PayRoll extends javax.swing.JPanel {

    /**
     * Creates new form Employee
     */
    public PayRoll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JEditorPane();
        txtPay = new javax.swing.JFormattedTextField();
        txtEmpoyeeNum = new javax.swing.JFormattedTextField();
        lbName = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel1.setText("員工編號");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 62, -1, -1));

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel2.setText("薪資");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 247, 60, 30));

        jLabel7.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel10.setText("備註");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 67, -1, -1));

        txtNote.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(txtNote);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 62, 254, 216));

        txtPay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtPay.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(txtPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 248, 225, 30));

        txtEmpoyeeNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtEmpoyeeNum.setToolTipText("");
        txtEmpoyeeNum.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        txtEmpoyeeNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmpoyeeNumKeyReleased(evt);
            }
        });
        add(txtEmpoyeeNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 62, 225, 31));

        lbName.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 106, 225, 29));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpoyeeNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpoyeeNumKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpoyeeNumKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbName;
    private javax.swing.JFormattedTextField txtEmpoyeeNum;
    private javax.swing.JEditorPane txtNote;
    private javax.swing.JFormattedTextField txtPay;
    // End of variables declaration//GEN-END:variables
}
