/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class pickingP extends javax.swing.JPanel {

    /**
     * Creates new form pickingP
     */
    public pickingP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pickingLabel01 = new javax.swing.JLabel();
        pickingid = new javax.swing.JLabel();
        pickingDate = new com.toedter.calendar.JDateChooser();
        pickingLabel04 = new javax.swing.JLabel();
        pickingLabel03 = new javax.swing.JLabel();
        pickingLabel0２ = new javax.swing.JLabel();
        materialNum = new javax.swing.JComboBox<>();
        materialName = new javax.swing.JLabel();
        employeeNum = new javax.swing.JComboBox<>();
        employeeName = new javax.swing.JLabel();
        pickingLabel05 = new javax.swing.JLabel();
        pickingLabel06 = new javax.swing.JLabel();
        pickingqty = new javax.swing.JSpinner();
        pickingLabel07 = new javax.swing.JLabel();
        pickingUnit = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        remark_picking = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        stockNum = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(980, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 470));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pickingLabel01.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        pickingLabel01.setText("領料單ID");
        jPanel1.add(pickingLabel01, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 53, -1, 30));

        pickingid.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        pickingid.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(pickingid, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 53, 180, 30));

        pickingDate.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jPanel1.add(pickingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 282, 30));

        pickingLabel04.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        pickingLabel04.setText("備註");
        jPanel1.add(pickingLabel04, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 88, 31));

        pickingLabel03.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        pickingLabel03.setText("領料人員");
        jPanel1.add(pickingLabel03, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 73, 30));

        pickingLabel0２.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        pickingLabel0２.setText("原料編號");
        jPanel1.add(pickingLabel0２, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 138, 88, 30));

        materialNum.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        materialNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        materialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialNumActionPerformed(evt);
            }
        });
        jPanel1.add(materialNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 138, 180, 30));

        materialName.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jPanel1.add(materialName, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 138, 160, 30));

        employeeNum.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        employeeNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employeeNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNumActionPerformed(evt);
            }
        });
        jPanel1.add(employeeNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 180, -1));

        employeeName.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jPanel1.add(employeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 115, 31));

        pickingLabel05.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        pickingLabel05.setText("領料日期");
        jPanel1.add(pickingLabel05, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 138, 75, 30));

        pickingLabel06.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        pickingLabel06.setText("領料數量");
        jPanel1.add(pickingLabel06, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 226, 75, 31));

        pickingqty.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jPanel1.add(pickingqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 229, 116, -1));

        pickingLabel07.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        pickingLabel07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pickingLabel07.setText("單位");
        jPanel1.add(pickingLabel07, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 226, -1, 33));

        pickingUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(pickingUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 229, 122, 30));

        remark_picking.setColumns(20);
        remark_picking.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        remark_picking.setRows(5);
        jScrollPane1.setViewportView(remark_picking);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 316, 343, 139));

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel1.setText("庫存量");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 232, -1, -1));

        stockNum.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jPanel1.add(stockNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 227, 180, 31));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void materialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialNumActionPerformed

    private void employeeNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel employeeName;
    private javax.swing.JComboBox<String> employeeNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel materialName;
    private javax.swing.JComboBox<String> materialNum;
    private com.toedter.calendar.JDateChooser pickingDate;
    private javax.swing.JLabel pickingLabel01;
    private javax.swing.JLabel pickingLabel03;
    private javax.swing.JLabel pickingLabel04;
    private javax.swing.JLabel pickingLabel05;
    private javax.swing.JLabel pickingLabel06;
    private javax.swing.JLabel pickingLabel07;
    private javax.swing.JLabel pickingLabel0２;
    private javax.swing.JComboBox<String> pickingUnit;
    private javax.swing.JLabel pickingid;
    private javax.swing.JSpinner pickingqty;
    private javax.swing.JTextArea remark_picking;
    private javax.swing.JLabel stockNum;
    // End of variables declaration//GEN-END:variables
}
