
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 許哲浩
 */
public class Product extends javax.swing.JPanel {
    /**
     * Creates new form orderList
     */
    public Product() {
        initComponents();

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_productNum = new javax.swing.JLabel();
        label_price = new javax.swing.JLabel();
        label_productName = new javax.swing.JLabel();
        label_category = new javax.swing.JLabel();
        label_note = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_note = new javax.swing.JTextArea();
        CBcategory = new javax.swing.JComboBox<>();
        text_price = new javax.swing.JTextField();
        label_pNum = new javax.swing.JLabel();
        text_productName = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(980, 470));
        setPreferredSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_productNum.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_productNum.setText("產品編號");
        add(label_productNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        label_price.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_price.setText("單價");
        add(label_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        label_productName.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_productName.setText("品名");
        add(label_productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 20));

        label_category.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_category.setText("類別");
        add(label_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        label_note.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_note.setText("備註");
        add(label_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        text_note.setColumns(20);
        text_note.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_note.setRows(5);
        jScrollPane2.setViewportView(text_note);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 630, -1));

        add(CBcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 200, 35));

        text_price.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_priceKeyTyped(evt);
            }
        });
        add(text_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 200, 35));

        label_pNum.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(label_pNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 200, 35));

        text_productName.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        add(text_productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void text_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_priceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_text_priceKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBcategory;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_category;
    private javax.swing.JLabel label_note;
    private javax.swing.JLabel label_pNum;
    private javax.swing.JLabel label_price;
    private javax.swing.JLabel label_productName;
    private javax.swing.JLabel label_productNum;
    private javax.swing.JTextArea text_note;
    private javax.swing.JTextField text_price;
    private javax.swing.JTextField text_productName;
    // End of variables declaration//GEN-END:variables
}
