
import com.sun.glass.events.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class purchaseP extends javax.swing.JPanel {

    /**
     * Creates new form purchaseP
     */
    public purchaseP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchaseLabel01 = new javax.swing.JLabel();
        purchaseNum_Purc = new javax.swing.JTextField();
        purchaseLabel02 = new javax.swing.JLabel();
        purchaseLabel03 = new javax.swing.JLabel();
        purchaseLabel04 = new javax.swing.JLabel();
        purchaseDate_Purc = new com.toedter.calendar.JDateChooser();
        purchaseLabel05 = new javax.swing.JLabel();
        purchaseLabel06 = new javax.swing.JLabel();
        qty_Purc = new javax.swing.JTextField();
        purchaseLabel07 = new javax.swing.JLabel();
        price_Purc = new javax.swing.JTextField();
        purchaseLabel08 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        note_Purc = new javax.swing.JTextArea();
        materialName_Purc = new javax.swing.JLabel();
        employName_Purc = new javax.swing.JLabel();
        vendorName_Purc = new javax.swing.JLabel();
        materialNum_Purc = new javax.swing.JComboBox<>();
        employNum_Purc = new javax.swing.JComboBox<>();
        vendorNum_Purc = new javax.swing.JComboBox<>();
        showInfo = new javax.swing.JLabel();
        SQLID = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purchaseLabel01.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel01.setText("進貨單號");
        add(purchaseLabel01, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 53, -1, 30));

        purchaseNum_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        purchaseNum_Purc.setPreferredSize(new java.awt.Dimension(10, 26));
        add(purchaseNum_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 55, 180, 30));

        purchaseLabel02.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel02.setText("原料編號");
        add(purchaseLabel02, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 124, -1, 30));

        purchaseLabel03.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel03.setText("進貨日期");
        add(purchaseLabel03, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 195, -1, 30));

        purchaseLabel04.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel04.setText("採購人員");
        add(purchaseLabel04, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 260, -1, 30));

        purchaseDate_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(purchaseDate_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 195, 180, 30));

        purchaseLabel05.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel05.setText("廠商編號");
        add(purchaseLabel05, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 53, -1, 30));

        purchaseLabel06.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel06.setText("進貨數量");
        purchaseLabel06.setToolTipText("");
        add(purchaseLabel06, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 124, -1, 30));

        qty_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        qty_Purc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qty_PurcKeyTyped(evt);
            }
        });
        add(qty_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 126, 150, 30));

        purchaseLabel07.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel07.setText("採購單價");
        add(purchaseLabel07, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 193, -1, 30));

        price_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        price_Purc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                price_PurcKeyTyped(evt);
            }
        });
        add(price_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 195, 150, 30));

        purchaseLabel08.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        purchaseLabel08.setText("備註");
        add(purchaseLabel08, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 265, -1, 30));

        note_Purc.setColumns(20);
        note_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        note_Purc.setRows(5);
        jScrollPane4.setViewportView(note_Purc);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 350, 170));

        materialName_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        materialName_Purc.setText("原料名稱");
        add(materialName_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 124, 120, 30));

        employName_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employName_Purc.setText("員工姓名");
        add(employName_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 260, 120, 30));

        vendorName_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        vendorName_Purc.setText("廠商名稱");
        add(vendorName_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 65, 187, -1));

        materialNum_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        materialNum_Purc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        materialNum_Purc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialNum_PurcActionPerformed(evt);
            }
        });
        add(materialNum_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 126, 180, 30));

        employNum_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        employNum_Purc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employNum_Purc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employNum_PurcActionPerformed(evt);
            }
        });
        add(employNum_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 260, 180, 30));

        vendorNum_Purc.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        vendorNum_Purc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vendorNum_Purc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorNum_PurcActionPerformed(evt);
            }
        });
        add(vendorNum_Purc, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 55, 150, 30));

        showInfo.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        showInfo.setText("系統編號");
        add(showInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 80, 40));

        SQLID.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        SQLID.setText("jLabel1");
        add(SQLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 328, 183, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void employNum_PurcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employNum_PurcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employNum_PurcActionPerformed

    private void materialNum_PurcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialNum_PurcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialNum_PurcActionPerformed

    private void vendorNum_PurcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorNum_PurcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorNum_PurcActionPerformed

    private void qty_PurcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_PurcKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c == KeyEvent.VK_SPACE) || (c == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_qty_PurcKeyTyped

    private void price_PurcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_price_PurcKeyTyped
       char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c == KeyEvent.VK_SPACE) || (c == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_price_PurcKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SQLID;
    private javax.swing.JLabel employName_Purc;
    private javax.swing.JComboBox<String> employNum_Purc;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel materialName_Purc;
    private javax.swing.JComboBox<String> materialNum_Purc;
    private javax.swing.JTextArea note_Purc;
    private javax.swing.JTextField price_Purc;
    private com.toedter.calendar.JDateChooser purchaseDate_Purc;
    private javax.swing.JLabel purchaseLabel01;
    private javax.swing.JLabel purchaseLabel02;
    private javax.swing.JLabel purchaseLabel03;
    private javax.swing.JLabel purchaseLabel04;
    private javax.swing.JLabel purchaseLabel05;
    private javax.swing.JLabel purchaseLabel06;
    private javax.swing.JLabel purchaseLabel07;
    private javax.swing.JLabel purchaseLabel08;
    private javax.swing.JTextField purchaseNum_Purc;
    private javax.swing.JTextField qty_Purc;
    private javax.swing.JLabel showInfo;
    private javax.swing.JLabel vendorName_Purc;
    private javax.swing.JComboBox<String> vendorNum_Purc;
    // End of variables declaration//GEN-END:variables
}
