
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.LinkedList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 許哲浩
 */
public class vendor extends javax.swing.JPanel {
    private Connection conn;
    /**
     * Creates new form vendor
     */
    public vendor() {
        initComponents();
        init();
    }
    private void init(){ 
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=erp;user=sa;password=00000000;");
            
            System.out.println("conn OK");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    protected void insert(){
        try{
            PreparedStatement pstmt = conn.prepareStatement(
                    "INSERT INTO vendor(vendorName,tel,address,taxId,contactPerson,paymentTerm,note) VALUES('"
                            + ""+text_vendorName.getText()+"','"
                            + ""+text_vendorTel.getText()+"','"
                            + ""+text_vendorAddr.getText()+"','"
                            + ""+text_taxId.getText()+"','"
                            + ""+text_contactPerson.getText()+"','"
                            + ""+text_paymentTerm.getText()+"','"
                            + ""+text_note.getText()+"')");
            pstmt.executeUpdate();
            
           textClear();
            
            pstmt.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    protected LinkedList select(){
        try{
            PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM vendor");
            ResultSet result =  pstmt.executeQuery();
            
            
            LinkedList<String[]> rows = new LinkedList<String[]>();
            
            while(result.next()){
                String[] row = new String[8];
                row[0] = result.getString("vendorNum");
                row[1] = result.getString("vendorName");
                row[2] = result.getString("tel");
                row[3] = result.getString("address");
                row[4] = result.getString("taxId");
                row[5] = result.getString("contactPerson");
                row[6] = result.getString("paymentTerm");
                row[7] = result.getString("note");

                rows.add(row);
            }

            pstmt.close();
            return rows;
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }
    protected String[] getColumn(){ 
        String[] columnName = 
                new String[]{"vendorNum","vendorName","tel","address","taxId","contactPerson","paymentTerm","note"};
        return columnName;
    }
    
    private void textClear(){
        text_vendorName.setText("");
        text_vendorTel.setText("");
        text_vendorAddr.setText("");
        text_taxId.setText("");
        text_contactPerson.setText("");
        text_paymentTerm.setText("");
        
        text_note.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_vendorNum = new javax.swing.JLabel();
        label_vendorTel = new javax.swing.JLabel();
        label_vendorAddr = new javax.swing.JLabel();
        label_taxId = new javax.swing.JLabel();
        label_contactPerson = new javax.swing.JLabel();
        label_paymentTerm = new javax.swing.JLabel();
        label_note = new javax.swing.JLabel();
        text_vendorName = new javax.swing.JTextField();
        text_vendorTel = new javax.swing.JTextField();
        text_vendorAddr = new javax.swing.JTextField();
        text_taxId = new javax.swing.JTextField();
        text_contactPerson = new javax.swing.JTextField();
        text_paymentTerm = new javax.swing.JTextField();
        scroll_note = new javax.swing.JScrollPane();
        text_note = new javax.swing.JTextArea();
        label_hint = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(980, 470));
        setPreferredSize(new java.awt.Dimension(980, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_vendorNum.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_vendorNum.setText("廠商名稱");
        add(label_vendorNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        label_vendorTel.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_vendorTel.setText("廠商電話");
        add(label_vendorTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        label_vendorAddr.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_vendorAddr.setText("廠商地址");
        add(label_vendorAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 142, -1, 20));

        label_taxId.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_taxId.setText("統編");
        add(label_taxId, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 142, -1, -1));

        label_contactPerson.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_contactPerson.setText("聯絡人");
        add(label_contactPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 205, -1, -1));

        label_paymentTerm.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_paymentTerm.setText("付款條件");
        add(label_paymentTerm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 205, -1, 20));

        label_note.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        label_note.setText("備註");
        add(label_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        text_vendorName.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_vendorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 75, 200, 35));

        text_vendorTel.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_vendorTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_vendorTelKeyReleased(evt);
            }
        });
        add(text_vendorTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 75, 200, 35));

        text_vendorAddr.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_vendorAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 137, 200, 35));

        text_taxId.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_taxId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_taxIdKeyReleased(evt);
            }
        });
        add(text_taxId, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 137, 200, 35));

        text_contactPerson.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_contactPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 200, 35));

        text_paymentTerm.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        add(text_paymentTerm, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 200, 35));

        text_note.setColumns(20);
        text_note.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        text_note.setRows(5);
        scroll_note.setViewportView(text_note);

        add(scroll_note, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 660, -1));

        label_hint.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        label_hint.setForeground(java.awt.Color.red);
        label_hint.setText("格式 : 地區碼- XXXX-XXXX");
        label_hint.setToolTipText("");
        add(label_hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void text_taxIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_taxIdKeyReleased
        // TODO add your handling code here:
        String re = "\\d*?";
        if(text_taxId.getText().matches(re))
            text_taxId.setText("");
    }//GEN-LAST:event_text_taxIdKeyReleased

    private void text_vendorTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_vendorTelKeyReleased
        // TODO add your handling code here:
        String re = "\\d*?";
        String phoneNum = "\\(0\\d+?\\)\\d*?";
        String cellPhone = "^\\d{4}-\\d{6}\\d*?";
        if(text_vendorTel.getText().matches(phoneNum)){
            System.out.println("Phone Num : " + text_vendorTel.getText().length());
        }
        if(text_vendorTel.getText().matches(re))
            System.out.println("RE : " + text_vendorTel.getText().length());
        if(text_vendorTel.getText().matches(cellPhone))
            System.out.println("Cell phone : " + text_vendorTel.getText().length());
    }//GEN-LAST:event_text_vendorTelKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_contactPerson;
    private javax.swing.JLabel label_hint;
    private javax.swing.JLabel label_note;
    private javax.swing.JLabel label_paymentTerm;
    private javax.swing.JLabel label_taxId;
    private javax.swing.JLabel label_vendorAddr;
    private javax.swing.JLabel label_vendorNum;
    private javax.swing.JLabel label_vendorTel;
    private javax.swing.JScrollPane scroll_note;
    private javax.swing.JTextField text_contactPerson;
    private javax.swing.JTextArea text_note;
    private javax.swing.JTextField text_paymentTerm;
    private javax.swing.JTextField text_taxId;
    private javax.swing.JTextField text_vendorAddr;
    private javax.swing.JTextField text_vendorName;
    private javax.swing.JTextField text_vendorTel;
    // End of variables declaration//GEN-END:variables
}
