/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class webNews extends javax.swing.JPanel {

    /**
     * Creates new form webNews
     */
    public webNews() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPublish = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        rbPublish = new javax.swing.JRadioButton();
        rbPrivate = new javax.swing.JRadioButton();
        btnChooseFile = new javax.swing.JButton();
        btnWatchFile = new javax.swing.JButton();
        lbFilePath = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        lbId = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(980, 470));
        setMinimumSize(new java.awt.Dimension(980, 470));

        jPanel1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(980, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(980, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 73, 45, -1));

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel2.setText("標題");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 45, -1));

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel3.setText("內容");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel4.setText("上架");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 70, 44, -1));

        jLabel5.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 180, 30, -1));

        jLabel6.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        jLabel6.setText("備註");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        txtTitle.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        txtTitle.setText("jTextField2");
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 319, -1));

        txtContent.setColumns(20);
        txtContent.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 319, 141));

        bgPublish.add(rbPublish);
        rbPublish.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        rbPublish.setText("是");
        jPanel1.add(rbPublish, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 70, -1, -1));

        bgPublish.add(rbPrivate);
        rbPrivate.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        rbPrivate.setText("否");
        jPanel1.add(rbPrivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 70, -1, -1));

        btnChooseFile.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        btnChooseFile.setText("選擇檔案");
        jPanel1.add(btnChooseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 117, -1, -1));

        btnWatchFile.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        btnWatchFile.setText("查看檔案");
        jPanel1.add(btnWatchFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 117, -1, -1));

        lbFilePath.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        lbFilePath.setText("jLabel7");
        jPanel1.add(lbFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 430, 30));

        txtNote.setColumns(20);
        txtNote.setFont(new java.awt.Font("微軟正黑體", 0, 14)); // NOI18N
        txtNote.setRows(5);
        jScrollPane2.setViewportView(txtNote);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 318, -1));

        lbId.setFont(new java.awt.Font("微軟正黑體", 0, 15)); // NOI18N
        lbId.setText("jLabel7");
        jPanel1.add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 73, 316, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPublish;
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnWatchFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFilePath;
    private javax.swing.JLabel lbId;
    private javax.swing.JRadioButton rbPrivate;
    private javax.swing.JRadioButton rbPublish;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
